version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - es-kibana
  kibana:
    image: kibana:8.15.2
    container_name: kibana
    environment:
      ELASTICSERACH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - es-kibana
  zookeeper:
    image: zookeeper:3.9.3-jre-17
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - es-kibana
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - es-kibana
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  es-kibana:
    driver: bridge
